def generate_markdown(sector: str, analysis: str, sources: list[str]) -> str:
    report = f"""# 📊 Market Analysis Report: {sector.title()}

## 🔍 Sector Overview
{analysis}

## 📰 Data Sources
"""
    for source in sources:
        report += f"- {source}\n"

    report += "\n---\n*Generated by Trade Opportunities API*"
    return report
